VARIABLES = [
    "Size of Public sector - Civil servants - General public services expenditure",
    "Legal framework quality/efficiency",
    "Administrative quality and efficiency",
    "Social trust and social capital",
    "Access to education",
    "Access to health services",
    "Access to digital services",
    "Adequate transportation infrastructure - Road traffic deaths",
    "Presence of social (hard) infrastructure",
    "Credible property rights",
    "Credible human and civic rights",
    "Environmental quality",
    "Ethnic and geographical origins",
    "Level of development",
    "Economic growth",
    "Economic attractiveness of place",
    "Demographic dynamics",
    "Labor market imbalances",
    "Oligopolistic market structure - The presence of Super-star firms",
    "Specialization in knowledge intensive sectors - Digitalization and AI",
    "Min wage level",
    "Collective bargaining",
    "EU integration: Expand commodity trade with the EU",
    "EU integration: Expand trade in services with the EU",
    "EU integration: Labor mobility in the EU",
    "EU integration: Capital mobility (FDI) in the EU",
    "Globalization: trade competition",
    "Globalization: the location patterns of FDI",
    "Globalization: global value chains",
    "Agglomeration economies",
    "Innovation - R&D",
    "Wages and employee compensation",
    "Renewable energy",
    "Financialization of the economy",
    "Housing cost",
    "Public Investment (PI)",
    "Social welfare benefits",
    "Progressive taxation",
    "Tax shelters",
    "Profit taxation of business",
    "Income taxation of households",
    "Taxation of trade (Tariffs)",
    "Social Housing policy",
    "Social and solidarity economy",
    "Cohesion Policy (CP)",
    "Common Agricultural Policy (CAP)",
    "Next Generation EU (RRF)",
    "Policies for human capital",
    "Policies for Investment",
    "Policies for Infrastructure",
    "Policies for Environment",
    "Policies for Green Transition",
    "Policies for Smart Transition / Industry 4.0 / R&D",
    "Local Government empowerment",
    "Inequalities in Access to education",
    "Inequalities in Access to health services",
    "Inequalities in Access to digital services",
    "Access to affordable housing",
    "Inequalities in Environmental quality",
    "Neighborhood conditions",
    "Democratic voice / quality",
    "Unequal Income distribution (individuals or social groups)",
    "Unequal well-being distribution (individuals or social groups)",
    "Unequal development (regions or countries)",
    "Unequal well-being (regions or countries)",
    "Perceived income inequalities",
    "Discrimination with respect to Gender",
    "Discrimination with respect to race - Discrimination minorities",
    "Discrimination with respect to origin",
    "Social cohesion",
    "Climate change",
    "Immigration due to shocks",
    "Natural disasters",
    "Covid-19",
    "War in the ENP area",
    "Energy crisis",
    "Discontent",
    "Democracy",
    "Anti-systemic vote"
]